spring:
  application:
    name: e-commerceplatforms
#MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e-commerceplatform?serverTimezone=Asia/Shanghai
    username: root
    password: "031003"
#允许循环依赖
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true
#SpringMail配置
  mail:
    host: smtp.qq.com          # QQ SMTP 服务器
    port: 587                  # STARTTLS 端口（或 465 SSL）
    username: 3165069523@qq.com
    password: isgselvqtkuudebi # 你的授权码（16 位）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
#redis配置
  data:
    redis:
      host: localhost #热点:172.16.2.249 主机：192.0.0.225
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
#debug
logging:
  level:
    com.yyblcc.ecommerceplatforms: debug
#Mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted  # 全局逻辑删除字段值
      logic-delete-value: 1          # 逻辑已删除值
      logic-not-delete-value: 0
      type-enums-package: com.yyblcc.ecommerceplatforms.entity.Enum
  configuration:
    map-underscore-to-camel-case: true
#设置session有效期为30min
server:
  servlet:
    session:
      timeout: 30m
#SpringMail附属配置
app:
  verify-code:
    length: 6
    expire-seconds: 300                 # 5 分钟
    send-limit-seconds: 60