spring:
  application:
    name: e-commerceplatforms
#MySQL配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e-commerceplatform?serverTimezone=Asia/Shanghai
    username: root
    password: "031003"
#允许循环依赖
  main:
    allow-circular-references: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: true
#SpringMail配置
  mail:
    host: smtp.qq.com          # QQ SMTP 服务器
    port: 587                  # STARTTLS 端口（或 465 SSL）
    username: 3165069523@qq.com
    password: isgselvqtkuudebi # 你的授权码（16 位）
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
#redis配置
  data:
    redis:
      host: localhost #热点:172.16.2.249 主机：192.0.0.225
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
#debug
logging:
  level:
    com.yyblcc.ecommerceplatforms: debug
#Mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDeleted  # 全局逻辑删除字段值
      logic-delete-value: 1          # 逻辑已删除值
      logic-not-delete-value: 0
      type-enums-package: com.yyblcc.ecommerceplatforms.entity.Enum
  configuration:
    map-underscore-to-camel-case: true
#设置session有效期为30min
server:
  servlet:
    session:
      timeout: 30m
#SpringMail附属配置
app:
  verify-code:
    length: 6
    expire-seconds: 300                 # 5 分钟
    send-limit-seconds: 60
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: my-producer-group
  consumer:
    group: my-consumer-group
alipay:
  appId: 9021000153674261
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCe+c193oAXQK7FY3WbLyY6dSdsSKEqy/3Cc96EYEiW6G190oeOhQUcnjTm/qR6EJ9mdLXmfd9h6/VYGJ0H9AtDqFtVdgEFpQxfkaY3BhI0iWQPgIvMZF3OFEtsVrlyC2n1hXROJQparukASXjzga5lFb6Ue/GCtY0ZPz2GaI1RmbdHImRZTaPVlhLXD4h5eTqx0GqAHE8thTo/8jm0bVvFWbukB3MP1+Zt1MBSsalIvVdgb5M3ufWDfoaDGWNU9wTxLkNZfuQ2wcEJqDPwRO854kImFS2Cax9JtUyTlMwwUkU/v/UShuxQgH8SEi+TUM0hKe5r6e56d0fkes78vautAgMBAAECggEALhbN9IflKtid0qwbFHp+4sPEQihsUTQCxbVB9a7UXKvV0nyOwErgSIO1YqLAnILlM5byhXhIouL9piS8oemmul682/HyKejHxY08Wwdvj7ulPrlNzlvqtiw8EZSy/tVASuX96gnjDpdXBbZHUpFuNfAv6GxmgDaSSZeEBsuY7ObmdPl7Yod4uzdZlcl3A4kQ/OZTMQT5vP67AgH5MH1J+SSOEAwlnrbkvlLHn9bybLT8CkQYmUtbFzMTDjg/uXB/qMJg5fHeqat0q3s8z/Nb5K0+RI0jtaEU9FBSRMhQ6UBUzmuKg32fVStCR7rWIEcOdguMKOQxViU+isrYrB4lAQKBgQDX88TwrSIN5CMt2kKvxcWIEddIIujiaIR4aj52Wk0P2idIgyG1XJa058VP3el0vuyeO6utIYoXYLowktXVZfTAsQm8bAnPFTZZ4FHAnywEfRQp8h/Cg4I2umgoZ1cXkV30S7EHp4GCh+ym9S+IV29tT/03UnFJ3sp5E0zdG9+rlQKBgQC8dRqeFmmFTq+D6GMKU1ZKhxVEHGrKoKvtQ5SRoL+vGy7nQ3fTwi00r+OYu/E+FRZYW9gETYmY5omPX3VF6FKpqdtQ0BnwOCbblqMxToIRU18jtlaIYozt4GVOJFZroFbBEjwUIKUC6ixEE96xpcSA8o/1qlXnnyS24yle+ay5uQKBgE3oEIVvQFjYk+Rn2CUHaUK0hQDuLyv23st+MLiLzT9JyWA8hn2iQHBVKPauLRnEAyL2jfGwptvWNnVtk50f4hNeCxAhvcwqb+gup++gvMWFxi93vQN0ZBaQWyEwXtgOxmFqqRwEzxEjLjnxPEuol3dNIyHBKUOoD01srA8cji2dAoGASPKrUvYp8kf6+HxDmgOYK1EOkkbNr5Fx+21lXNl0WTuUdEBRac6H4RUUbFKTlwxikeE7RK8ey+iw5qZ0ppK/LJ1rH2TuJWYW5Hjywms5Pauf8Brsc+5xzsJFdHHsYcy2yBVe3Aum0/IBIHjwgqM/5Qn/X4CHsBiSBZj4sqLCkUECgYEAsMAl3IQJmpeZJSJXkIBr1JdC889J1TprZxqhkCZMq5s4nykX1bWMFer30OHP9BFuB1XtGTlFpgV69LNRm2EtIa4r6oEqwinsHDjTXJtIwqcpOuIWgvI/ljW3tcTsE6SBQdQ00d5lmWa30CZ6Ezgv0bImNVSy4RMUQaflm0+wyYY=
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnvnNfd6AF0CuxWN1my8mOnUnbEihKsv9wnPehGBIluhtfdKHjoUFHJ405v6kehCfZnS15n3fYev1WBidB/QLQ6hbVXYBBaUMX5GmNwYSNIlkD4CLzGRdzhRLbFa5cgtp9YV0TiUKWq7pAEl484GuZRW+lHvxgrWNGT89hmiNUZm3RyJkWU2j1ZYS1w+IeXk6sdBqgBxPLYU6P/I5tG1bxVm7pAdzD9fmbdTAUrGpSL1XYG+TN7n1g36GgxljVPcE8S5DWX7kNsHBCagz8ETvOeJCJhUtgmsfSbVMk5TMMFJFP7/1EobsUIB/EhIvk1DNISnua+nuendH5HrO/L2rrQIDAQAB
  serverUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  notifyUrl: http://zc964c65.natappfree.cc